"""description

Revision ID: d87beb3235ad
Revises: 
Create Date: 2024-06-10 19:42:22.948140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd87beb3235ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition_awards', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='序号',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('event_name',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='赛事名称',
               existing_nullable=True)
        batch_op.alter_column('work_name',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='作品名称',
               existing_nullable=True)
        batch_op.alter_column('award_category',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='获奖类别',
               existing_nullable=True)
        batch_op.alter_column('award_level',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='获奖等级',
               existing_nullable=True)
        batch_op.alter_column('teacher_name',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='指导教师',
               existing_nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='指导教师工号',
               existing_nullable=True)
        batch_op.alter_column('total_workload',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(precision=6, asdecimal=True),
               comment=None,
               existing_comment='总工作量',
               existing_nullable=True)
        batch_op.alter_column('award_year',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='获奖年份',
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_competition_awards_teacher_id'), ['teacher_id'], unique=False)
        batch_op.drop_constraint('competition_awards_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'teacher_information', ['teacher_id'], ['teacher_id'])

    with op.batch_alter_table('department_internship', schema=None) as batch_op:
        batch_op.alter_column('student_name',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='学生姓名',
               existing_nullable=True)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='学生学号',
               existing_nullable=False)
        batch_op.alter_column('major',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='专业',
               existing_nullable=True)
        batch_op.alter_column('grade',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='年级',
               existing_nullable=True)
        batch_op.alter_column('teacher_name',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='学部内实习指导教师',
               existing_nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='学部内实习指导教师工号',
               existing_nullable=True)
        batch_op.alter_column('week',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='实习周数',
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_department_internship_teacher_id'), ['teacher_id'], unique=False)
        batch_op.drop_constraint('department_internship_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'teacher_information', ['teacher_id'], ['teacher_id'])

    with op.batch_alter_table('educational_research_project', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='序号，主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('project_name',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='项目名称',
               existing_nullable=True)
        batch_op.alter_column('project_leader',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='项目负责人',
               existing_nullable=True)
        batch_op.alter_column('project_members',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='项目成员100',
               existing_nullable=True)
        batch_op.alter_column('project_level',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='级别',
               existing_nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='立项时间',
               existing_nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='结项时间',
               existing_nullable=True)
        batch_op.alter_column('acceptance_result',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='验收结论',
               existing_nullable=True)
        batch_op.alter_column('teacher_name',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='教师姓名',
               existing_nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='工号',
               existing_nullable=True)
        batch_op.alter_column('research_project_workload',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(precision=6, asdecimal=True),
               comment=None,
               existing_comment='教研项目工作量',
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_educational_research_project_teacher_id'), ['teacher_id'], unique=False)
        batch_op.drop_constraint('educational_research_project_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'teacher_information', ['teacher_id'], ['teacher_id'])

    with op.batch_alter_table('first_class_courses', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='序号',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('course_type',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='课程性质',
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='内容',
               existing_nullable=True)
        batch_op.alter_column('leader',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='负责人',
               existing_nullable=True)
        batch_op.alter_column('remark',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='备注，工作量分配',
               existing_nullable=True)
        batch_op.alter_column('teacher_name',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='教师姓名，一位老师一个记录',
               existing_nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='工号，外键',
               existing_nullable=True)
        batch_op.alter_column('first_class_course_workload',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(precision=6, asdecimal=True),
               comment=None,
               existing_comment='一流课程工作量',
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_first_class_courses_teacher_id'), ['teacher_id'], unique=False)
        batch_op.drop_constraint('first_class_courses_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'teacher_information', ['teacher_id'], ['teacher_id'])

    with op.batch_alter_table('public_services', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='序号，主键，自增，无意义',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('serve_date',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='日期',
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='内容',
               existing_nullable=True)
        batch_op.alter_column('teacher_name',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='姓名',
               existing_nullable=True)
        batch_op.alter_column('work_duration',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(precision=6, asdecimal=True),
               comment=None,
               existing_comment='工作时长',
               existing_nullable=True)
        batch_op.alter_column('class_hours',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(precision=6, asdecimal=True),
               comment=None,
               existing_comment='课时',
               existing_nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='教师工号，外键',
               existing_nullable=True)
        batch_op.alter_column('workload',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='工作量',
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_public_services_teacher_id'), ['teacher_id'], unique=False)
        batch_op.drop_constraint('public_services_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'teacher_information', ['teacher_id'], ['teacher_id'])

    with op.batch_alter_table('student_research', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='序号',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('project_name',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='项目名称',
               existing_nullable=True)
        batch_op.alter_column('project_level',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='级别',
               existing_nullable=True)
        batch_op.alter_column('leader',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='负责人',
               existing_nullable=True)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='学号',
               existing_nullable=True)
        batch_op.alter_column('total_members',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='项目组总人数',
               existing_nullable=True)
        batch_op.alter_column('teacher_name',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='指导老师',
               existing_nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=mysql.VARCHAR(length=24),
               type_=sa.String(length=255),
               comment=None,
               existing_comment='指导老师工号',
               existing_nullable=True)
        batch_op.alter_column('acceptance_result',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='验收结果',
               existing_nullable=True)
        batch_op.alter_column('workload',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(precision=6, asdecimal=True),
               comment=None,
               existing_comment='工作量',
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_student_research_teacher_id'), ['teacher_id'], unique=False)
        batch_op.drop_constraint('student_research_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'teacher_information', ['teacher_id'], ['teacher_id'])

    with op.batch_alter_table('teacher_information', schema=None) as batch_op:
        batch_op.alter_column('teacher_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               comment=None,
               existing_comment='教工号',
               existing_nullable=False)
        batch_op.alter_column('teacher_name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               comment=None,
               existing_comment='教师姓名',
               existing_nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='hash密码',
               existing_nullable=True)

    with op.batch_alter_table('teaching_achievement_awards', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='序号，主键，自增，无意义',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('student_session',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='届',
               existing_nullable=True)
        batch_op.alter_column('student_date',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='时间',
               existing_nullable=True)
        batch_op.alter_column('recommended_achievement_name',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='推荐成果名称',
               existing_nullable=True)
        batch_op.alter_column('main_completion_person_name',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='成果主要完成人名称',
               existing_nullable=True)
        batch_op.alter_column('award_category',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='获奖类别',
               existing_nullable=True)
        batch_op.alter_column('award_level',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='获奖等级',
               existing_nullable=True)
        batch_op.alter_column('remark',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='备注',
               existing_nullable=True)
        batch_op.alter_column('teacher_name',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='教师',
               existing_nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=mysql.VARCHAR(length=24),
               type_=sa.String(length=255),
               comment=None,
               existing_comment='工号，外键',
               existing_nullable=True)
        batch_op.alter_column('teaching_achievement_workload',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(precision=6, asdecimal=True),
               comment=None,
               existing_comment='教学成果工作量',
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_teaching_achievement_awards_teacher_id'), ['teacher_id'], unique=False)
        batch_op.drop_constraint('teaching_achievement_awards_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'teacher_information', ['teacher_id'], ['teacher_id'])

    with op.batch_alter_table('undergraduate_mentorship_system', schema=None) as batch_op:
        batch_op.alter_column('teacher_name',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='导师姓名',
               existing_nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=mysql.VARCHAR(length=24),
               type_=sa.String(length=255),
               comment=None,
               existing_comment='教工号',
               existing_nullable=True)
        batch_op.alter_column('student_name',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='学生姓名',
               existing_nullable=True)
        batch_op.alter_column('grade',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='年级',
               existing_nullable=True)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='学号',
               existing_nullable=False)
        batch_op.alter_column('teacher_workload',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(precision=6, asdecimal=True),
               comment=None,
               existing_comment='教师工作量',
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_undergraduate_mentorship_system_teacher_id'), ['teacher_id'], unique=False)
        batch_op.drop_constraint('undergraduate_mentorship_system_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'teacher_information', ['teacher_id'], ['teacher_id'])

    with op.batch_alter_table('undergraduate_thesis', schema=None) as batch_op:
        batch_op.alter_column('student_name',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='学生姓名',
               existing_nullable=True)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='学生学号',
               existing_nullable=False)
        batch_op.alter_column('college',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='学院',
               existing_nullable=True)
        batch_op.alter_column('major',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='专业',
               existing_nullable=True)
        batch_op.alter_column('major_id',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='专业号',
               existing_nullable=True)
        batch_op.alter_column('grade',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='年级',
               existing_nullable=True)
        batch_op.alter_column('thesis_topic',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='毕业论文题目',
               existing_nullable=True)
        batch_op.alter_column('thesis_grade',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='毕业论文成绩',
               existing_nullable=True)
        batch_op.alter_column('teacher_name',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='毕业论文指导老师',
               existing_nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=mysql.VARCHAR(length=24),
               type_=sa.String(length=255),
               comment=None,
               existing_comment='毕业论文指导老师工号',
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_undergraduate_thesis_teacher_id'), ['teacher_id'], unique=False)
        batch_op.drop_constraint('undergraduate_thesis_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'teacher_information', ['teacher_id'], ['teacher_id'])

    with op.batch_alter_table('undergraduate_workload_course_ranking', schema=None) as batch_op:
        batch_op.alter_column('academic_year',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='学年',
               existing_nullable=True)
        batch_op.alter_column('semester',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='学期',
               existing_nullable=True)
        batch_op.alter_column('calendar_year',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='自然年',
               existing_nullable=True)
        batch_op.alter_column('half_year',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='上下半年',
               existing_nullable=True)
        batch_op.alter_column('course_code',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='课程号',
               existing_nullable=False)
        batch_op.alter_column('teaching_class',
               existing_type=mysql.VARCHAR(length=24),
               comment=None,
               existing_comment='教学班',
               existing_nullable=False)
        batch_op.alter_column('course_name',
               existing_type=mysql.VARCHAR(length=24),
               type_=sa.String(length=100),
               comment=None,
               existing_comment='课程名称',
               existing_nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=mysql.VARCHAR(length=56),
               type_=sa.String(length=30),
               comment=None,
               existing_comment='教工号',
               existing_nullable=True)
        batch_op.alter_column('teacher_name',
               existing_type=mysql.VARCHAR(length=12),
               type_=sa.String(length=50),
               comment=None,
               existing_comment='教师名称',
               existing_nullable=True)
        batch_op.alter_column('seminar_hours',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(),
               comment=None,
               existing_comment='研讨学时',
               existing_nullable=True)
        batch_op.alter_column('lecture_hours',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(),
               comment=None,
               existing_comment='授课学时',
               existing_nullable=True)
        batch_op.alter_column('lab_hours',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(),
               comment=None,
               existing_comment='实验学时',
               existing_nullable=True)
        batch_op.alter_column('enrolled_students',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='选课人数',
               existing_nullable=True)
        batch_op.alter_column('student_weight_coefficient_b',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(),
               comment=None,
               existing_comment='学生数量权重系数B',
               existing_nullable=True)
        batch_op.alter_column('course_type_coefficient_a',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(),
               comment=None,
               existing_comment='课程类型系数A',
               existing_nullable=True)
        batch_op.alter_column('total_lecture_hours_p1',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(),
               comment=None,
               existing_comment='理论课总学时P1',
               existing_nullable=True)
        batch_op.alter_column('lab_group_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='实验分组数',
               existing_nullable=True)
        batch_op.alter_column('lab_coefficient',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(),
               comment=None,
               existing_comment='实验课系数',
               existing_nullable=True)
        batch_op.alter_column('total_lab_hours_p2',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(),
               comment=None,
               existing_comment='实验课总学时P2',
               existing_nullable=True)
        batch_op.alter_column('course_split_ratio_for_engineering_center',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(),
               comment=None,
               existing_comment='课程拆分占比（工程中心用）',
               existing_nullable=True)
        batch_op.alter_column('total_course_hours',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(),
               comment=None,
               existing_comment='课程总学时',
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_undergraduate_workload_course_ranking_teacher_id'), ['teacher_id'], unique=False)
        batch_op.drop_constraint('undergraduate_workload_course_ranking_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'teacher_information', ['teacher_id'], ['teacher_id'])

    with op.batch_alter_table('undergraduate_workload_teacher_ranking', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='序号，自增',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('teacher_id',
               existing_type=mysql.VARCHAR(length=56),
               type_=sa.String(length=30),
               nullable=True,
               comment=None,
               existing_comment='教工号')
        batch_op.alter_column('teacher_name',
               existing_type=mysql.VARCHAR(length=12),
               type_=sa.String(length=50),
               comment=None,
               existing_comment='教师名称',
               existing_nullable=True)
        batch_op.alter_column('undergraduate_course_total_hours',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(),
               comment=None,
               existing_comment='本科课程总学时',
               existing_nullable=True)
        batch_op.alter_column('graduation_thesis_student_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='毕业论文学生人数',
               existing_nullable=True)
        batch_op.alter_column('graduation_thesis_p',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(),
               comment=None,
               existing_comment='毕业论文P',
               existing_nullable=True)
        batch_op.alter_column('teaching_internship_student_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='指导教学实习人数',
               existing_nullable=True)
        batch_op.alter_column('teaching_internship_weeks',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='指导教学实习周数',
               existing_nullable=True)
        batch_op.alter_column('teaching_internship_p',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(),
               comment=None,
               existing_comment='指导教学实习P',
               existing_nullable=True)
        batch_op.alter_column('responsible_internship_construction_management_p',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(),
               comment=None,
               existing_comment='负责实习点建设与管理P',
               existing_nullable=True)
        batch_op.alter_column('guiding_undergraduate_competition_p',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(),
               comment=None,
               existing_comment='指导本科生竞赛P',
               existing_nullable=True)
        batch_op.alter_column('guiding_undergraduate_research_p',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(),
               comment=None,
               existing_comment='指导本科生科研P',
               existing_nullable=True)
        batch_op.alter_column('undergraduate_tutor_system',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(),
               comment=None,
               existing_comment='本科生导师制',
               existing_nullable=True)
        batch_op.alter_column('teaching_research_and_reform_p',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(),
               comment=None,
               existing_comment='教研教改P',
               existing_nullable=True)
        batch_op.alter_column('first_class_course',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(),
               comment=None,
               existing_comment='一流课程',
               existing_nullable=True)
        batch_op.alter_column('teaching_achievement_award',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(),
               comment=None,
               existing_comment='教学成果奖',
               existing_nullable=True)
        batch_op.alter_column('public_service',
               existing_type=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               type_=sa.Float(),
               comment=None,
               existing_comment='公共服务',
               existing_nullable=True)
        batch_op.drop_constraint('1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'teacher_information', ['teacher_id'], ['teacher_id'])

    with op.batch_alter_table('workload_parameter', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='序号',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('graduation_thesis_p_count',
               existing_type=mysql.FLOAT(),
               nullable=True,
               comment=None,
               existing_comment='毕业论文参数')
        batch_op.alter_column('intership_count',
               existing_type=mysql.FLOAT(),
               nullable=True,
               comment=None,
               existing_comment='指导实习参数')
        batch_op.alter_column('intership_js',
               existing_type=mysql.FLOAT(),
               nullable=True,
               comment=None,
               existing_comment='实习点建设')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workload_parameter', schema=None) as batch_op:
        batch_op.alter_column('intership_js',
               existing_type=mysql.FLOAT(),
               nullable=False,
               comment='实习点建设')
        batch_op.alter_column('intership_count',
               existing_type=mysql.FLOAT(),
               nullable=False,
               comment='指导实习参数')
        batch_op.alter_column('graduation_thesis_p_count',
               existing_type=mysql.FLOAT(),
               nullable=False,
               comment='毕业论文参数')
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='序号',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('undergraduate_workload_teacher_ranking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('1', 'teacher_information', ['teacher_id'], ['teacher_id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.alter_column('public_service',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='公共服务',
               existing_nullable=True)
        batch_op.alter_column('teaching_achievement_award',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='教学成果奖',
               existing_nullable=True)
        batch_op.alter_column('first_class_course',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='一流课程',
               existing_nullable=True)
        batch_op.alter_column('teaching_research_and_reform_p',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='教研教改P',
               existing_nullable=True)
        batch_op.alter_column('undergraduate_tutor_system',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='本科生导师制',
               existing_nullable=True)
        batch_op.alter_column('guiding_undergraduate_research_p',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='指导本科生科研P',
               existing_nullable=True)
        batch_op.alter_column('guiding_undergraduate_competition_p',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='指导本科生竞赛P',
               existing_nullable=True)
        batch_op.alter_column('responsible_internship_construction_management_p',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='负责实习点建设与管理P',
               existing_nullable=True)
        batch_op.alter_column('teaching_internship_p',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='指导教学实习P',
               existing_nullable=True)
        batch_op.alter_column('teaching_internship_weeks',
               existing_type=mysql.INTEGER(),
               comment='指导教学实习周数',
               existing_nullable=True)
        batch_op.alter_column('teaching_internship_student_count',
               existing_type=mysql.INTEGER(),
               comment='指导教学实习人数',
               existing_nullable=True)
        batch_op.alter_column('graduation_thesis_p',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='毕业论文P',
               existing_nullable=True)
        batch_op.alter_column('graduation_thesis_student_count',
               existing_type=mysql.INTEGER(),
               comment='毕业论文学生人数',
               existing_nullable=True)
        batch_op.alter_column('undergraduate_course_total_hours',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='本科课程总学时',
               existing_nullable=True)
        batch_op.alter_column('teacher_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=12),
               comment='教师名称',
               existing_nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=56),
               nullable=False,
               comment='教工号')
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='序号，自增',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('undergraduate_workload_course_ranking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('undergraduate_workload_course_ranking_ibfk_1', 'teacher_information', ['teacher_id'], ['teacher_id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_undergraduate_workload_course_ranking_teacher_id'))
        batch_op.alter_column('total_course_hours',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='课程总学时',
               existing_nullable=True)
        batch_op.alter_column('course_split_ratio_for_engineering_center',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='课程拆分占比（工程中心用）',
               existing_nullable=True)
        batch_op.alter_column('total_lab_hours_p2',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='实验课总学时P2',
               existing_nullable=True)
        batch_op.alter_column('lab_coefficient',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='实验课系数',
               existing_nullable=True)
        batch_op.alter_column('lab_group_count',
               existing_type=mysql.INTEGER(),
               comment='实验分组数',
               existing_nullable=True)
        batch_op.alter_column('total_lecture_hours_p1',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='理论课总学时P1',
               existing_nullable=True)
        batch_op.alter_column('course_type_coefficient_a',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='课程类型系数A',
               existing_nullable=True)
        batch_op.alter_column('student_weight_coefficient_b',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='学生数量权重系数B',
               existing_nullable=True)
        batch_op.alter_column('enrolled_students',
               existing_type=mysql.INTEGER(),
               comment='选课人数',
               existing_nullable=True)
        batch_op.alter_column('lab_hours',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='实验学时',
               existing_nullable=True)
        batch_op.alter_column('lecture_hours',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='授课学时',
               existing_nullable=True)
        batch_op.alter_column('seminar_hours',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='研讨学时',
               existing_nullable=True)
        batch_op.alter_column('teacher_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=12),
               comment='教师名称',
               existing_nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=56),
               comment='教工号',
               existing_nullable=True)
        batch_op.alter_column('course_name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=24),
               comment='课程名称',
               existing_nullable=True)
        batch_op.alter_column('teaching_class',
               existing_type=mysql.VARCHAR(length=24),
               comment='教学班',
               existing_nullable=False)
        batch_op.alter_column('course_code',
               existing_type=mysql.VARCHAR(length=24),
               comment='课程号',
               existing_nullable=False)
        batch_op.alter_column('half_year',
               existing_type=mysql.VARCHAR(length=20),
               comment='上下半年',
               existing_nullable=True)
        batch_op.alter_column('calendar_year',
               existing_type=mysql.INTEGER(),
               comment='自然年',
               existing_nullable=True)
        batch_op.alter_column('semester',
               existing_type=mysql.VARCHAR(length=10),
               comment='学期',
               existing_nullable=True)
        batch_op.alter_column('academic_year',
               existing_type=mysql.VARCHAR(length=10),
               comment='学年',
               existing_nullable=True)

    with op.batch_alter_table('undergraduate_thesis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('undergraduate_thesis_ibfk_1', 'teacher_information', ['teacher_id'], ['teacher_id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_undergraduate_thesis_teacher_id'))
        batch_op.alter_column('teacher_id',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=24),
               comment='毕业论文指导老师工号',
               existing_nullable=True)
        batch_op.alter_column('teacher_name',
               existing_type=mysql.VARCHAR(length=24),
               comment='毕业论文指导老师',
               existing_nullable=True)
        batch_op.alter_column('thesis_grade',
               existing_type=mysql.VARCHAR(length=24),
               comment='毕业论文成绩',
               existing_nullable=True)
        batch_op.alter_column('thesis_topic',
               existing_type=mysql.VARCHAR(length=24),
               comment='毕业论文题目',
               existing_nullable=True)
        batch_op.alter_column('grade',
               existing_type=mysql.VARCHAR(length=24),
               comment='年级',
               existing_nullable=True)
        batch_op.alter_column('major_id',
               existing_type=mysql.VARCHAR(length=24),
               comment='专业号',
               existing_nullable=True)
        batch_op.alter_column('major',
               existing_type=mysql.VARCHAR(length=24),
               comment='专业',
               existing_nullable=True)
        batch_op.alter_column('college',
               existing_type=mysql.VARCHAR(length=24),
               comment='学院',
               existing_nullable=True)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=24),
               comment='学生学号',
               existing_nullable=False)
        batch_op.alter_column('student_name',
               existing_type=mysql.VARCHAR(length=24),
               comment='学生姓名',
               existing_nullable=True)

    with op.batch_alter_table('undergraduate_mentorship_system', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('undergraduate_mentorship_system_ibfk_1', 'teacher_information', ['teacher_id'], ['teacher_id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_undergraduate_mentorship_system_teacher_id'))
        batch_op.alter_column('teacher_workload',
               existing_type=sa.Float(precision=6, asdecimal=True),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='教师工作量',
               existing_nullable=True)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=24),
               comment='学号',
               existing_nullable=False)
        batch_op.alter_column('grade',
               existing_type=mysql.VARCHAR(length=24),
               comment='年级',
               existing_nullable=True)
        batch_op.alter_column('student_name',
               existing_type=mysql.VARCHAR(length=24),
               comment='学生姓名',
               existing_nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=24),
               comment='教工号',
               existing_nullable=True)
        batch_op.alter_column('teacher_name',
               existing_type=mysql.VARCHAR(length=24),
               comment='导师姓名',
               existing_nullable=True)

    with op.batch_alter_table('teaching_achievement_awards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('teaching_achievement_awards_ibfk_1', 'teacher_information', ['teacher_id'], ['teacher_id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_teaching_achievement_awards_teacher_id'))
        batch_op.alter_column('teaching_achievement_workload',
               existing_type=sa.Float(precision=6, asdecimal=True),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='教学成果工作量',
               existing_nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=24),
               comment='工号，外键',
               existing_nullable=True)
        batch_op.alter_column('teacher_name',
               existing_type=mysql.VARCHAR(length=24),
               comment='教师',
               existing_nullable=True)
        batch_op.alter_column('remark',
               existing_type=mysql.VARCHAR(length=24),
               comment='备注',
               existing_nullable=True)
        batch_op.alter_column('award_level',
               existing_type=mysql.VARCHAR(length=24),
               comment='获奖等级',
               existing_nullable=True)
        batch_op.alter_column('award_category',
               existing_type=mysql.VARCHAR(length=24),
               comment='获奖类别',
               existing_nullable=True)
        batch_op.alter_column('main_completion_person_name',
               existing_type=mysql.VARCHAR(length=24),
               comment='成果主要完成人名称',
               existing_nullable=True)
        batch_op.alter_column('recommended_achievement_name',
               existing_type=mysql.VARCHAR(length=24),
               comment='推荐成果名称',
               existing_nullable=True)
        batch_op.alter_column('student_date',
               existing_type=mysql.VARCHAR(length=24),
               comment='时间',
               existing_nullable=True)
        batch_op.alter_column('student_session',
               existing_type=mysql.VARCHAR(length=24),
               comment='届',
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='序号，主键，自增，无意义',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('teacher_information', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               comment='hash密码',
               existing_nullable=True)
        batch_op.alter_column('teacher_name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               comment='教师姓名',
               existing_nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               comment='教工号',
               existing_nullable=False)

    with op.batch_alter_table('student_research', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('student_research_ibfk_1', 'teacher_information', ['teacher_id'], ['teacher_id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_student_research_teacher_id'))
        batch_op.alter_column('workload',
               existing_type=sa.Float(precision=6, asdecimal=True),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='工作量',
               existing_nullable=True)
        batch_op.alter_column('acceptance_result',
               existing_type=mysql.VARCHAR(length=24),
               comment='验收结果',
               existing_nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=24),
               comment='指导老师工号',
               existing_nullable=True)
        batch_op.alter_column('teacher_name',
               existing_type=mysql.VARCHAR(length=24),
               comment='指导老师',
               existing_nullable=True)
        batch_op.alter_column('total_members',
               existing_type=mysql.INTEGER(),
               comment='项目组总人数',
               existing_nullable=True)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=24),
               comment='学号',
               existing_nullable=True)
        batch_op.alter_column('leader',
               existing_type=mysql.VARCHAR(length=24),
               comment='负责人',
               existing_nullable=True)
        batch_op.alter_column('project_level',
               existing_type=mysql.VARCHAR(length=24),
               comment='级别',
               existing_nullable=True)
        batch_op.alter_column('project_name',
               existing_type=mysql.VARCHAR(length=24),
               comment='项目名称',
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='序号',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('public_services', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('public_services_ibfk_1', 'teacher_information', ['teacher_id'], ['teacher_id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_public_services_teacher_id'))
        batch_op.alter_column('workload',
               existing_type=mysql.FLOAT(),
               comment='工作量',
               existing_nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=mysql.VARCHAR(length=24),
               comment='教师工号，外键',
               existing_nullable=True)
        batch_op.alter_column('class_hours',
               existing_type=sa.Float(precision=6, asdecimal=True),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='课时',
               existing_nullable=True)
        batch_op.alter_column('work_duration',
               existing_type=sa.Float(precision=6, asdecimal=True),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='工作时长',
               existing_nullable=True)
        batch_op.alter_column('teacher_name',
               existing_type=mysql.VARCHAR(length=24),
               comment='姓名',
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(length=24),
               comment='内容',
               existing_nullable=True)
        batch_op.alter_column('serve_date',
               existing_type=mysql.VARCHAR(length=24),
               comment='日期',
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='序号，主键，自增，无意义',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('first_class_courses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('first_class_courses_ibfk_1', 'teacher_information', ['teacher_id'], ['teacher_id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_first_class_courses_teacher_id'))
        batch_op.alter_column('first_class_course_workload',
               existing_type=sa.Float(precision=6, asdecimal=True),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='一流课程工作量',
               existing_nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=mysql.VARCHAR(length=24),
               comment='工号，外键',
               existing_nullable=True)
        batch_op.alter_column('teacher_name',
               existing_type=mysql.VARCHAR(length=24),
               comment='教师姓名，一位老师一个记录',
               existing_nullable=True)
        batch_op.alter_column('remark',
               existing_type=mysql.VARCHAR(length=24),
               comment='备注，工作量分配',
               existing_nullable=True)
        batch_op.alter_column('leader',
               existing_type=mysql.VARCHAR(length=24),
               comment='负责人',
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(length=24),
               comment='内容',
               existing_nullable=True)
        batch_op.alter_column('course_type',
               existing_type=mysql.VARCHAR(length=24),
               comment='课程性质',
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='序号',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('educational_research_project', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('educational_research_project_ibfk_1', 'teacher_information', ['teacher_id'], ['teacher_id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_educational_research_project_teacher_id'))
        batch_op.alter_column('research_project_workload',
               existing_type=sa.Float(precision=6, asdecimal=True),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='教研项目工作量',
               existing_nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=mysql.VARCHAR(length=24),
               comment='工号',
               existing_nullable=True)
        batch_op.alter_column('teacher_name',
               existing_type=mysql.VARCHAR(length=24),
               comment='教师姓名',
               existing_nullable=True)
        batch_op.alter_column('acceptance_result',
               existing_type=mysql.VARCHAR(length=24),
               comment='验收结论',
               existing_nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               comment='结项时间',
               existing_nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               comment='立项时间',
               existing_nullable=True)
        batch_op.alter_column('project_level',
               existing_type=mysql.VARCHAR(length=24),
               comment='级别',
               existing_nullable=True)
        batch_op.alter_column('project_members',
               existing_type=mysql.VARCHAR(length=24),
               comment='项目成员100',
               existing_nullable=True)
        batch_op.alter_column('project_leader',
               existing_type=mysql.VARCHAR(length=24),
               comment='项目负责人',
               existing_nullable=True)
        batch_op.alter_column('project_name',
               existing_type=mysql.VARCHAR(length=24),
               comment='项目名称',
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='序号，主键',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('department_internship', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('department_internship_ibfk_1', 'teacher_information', ['teacher_id'], ['teacher_id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_department_internship_teacher_id'))
        batch_op.alter_column('week',
               existing_type=mysql.VARCHAR(length=24),
               comment='实习周数',
               existing_nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=mysql.VARCHAR(length=24),
               comment='学部内实习指导教师工号',
               existing_nullable=True)
        batch_op.alter_column('teacher_name',
               existing_type=mysql.VARCHAR(length=24),
               comment='学部内实习指导教师',
               existing_nullable=True)
        batch_op.alter_column('grade',
               existing_type=mysql.VARCHAR(length=24),
               comment='年级',
               existing_nullable=True)
        batch_op.alter_column('major',
               existing_type=mysql.VARCHAR(length=24),
               comment='专业',
               existing_nullable=True)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=24),
               comment='学生学号',
               existing_nullable=False)
        batch_op.alter_column('student_name',
               existing_type=mysql.VARCHAR(length=24),
               comment='学生姓名',
               existing_nullable=True)

    with op.batch_alter_table('competition_awards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('competition_awards_ibfk_1', 'teacher_information', ['teacher_id'], ['teacher_id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_competition_awards_teacher_id'))
        batch_op.alter_column('award_year',
               existing_type=mysql.VARCHAR(length=24),
               comment='获奖年份',
               existing_nullable=True)
        batch_op.alter_column('total_workload',
               existing_type=sa.Float(precision=6, asdecimal=True),
               type_=mysql.DOUBLE(precision=6, scale=2, asdecimal=True),
               comment='总工作量',
               existing_nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=mysql.VARCHAR(length=24),
               comment='指导教师工号',
               existing_nullable=True)
        batch_op.alter_column('teacher_name',
               existing_type=mysql.VARCHAR(length=24),
               comment='指导教师',
               existing_nullable=True)
        batch_op.alter_column('award_level',
               existing_type=mysql.VARCHAR(length=24),
               comment='获奖等级',
               existing_nullable=True)
        batch_op.alter_column('award_category',
               existing_type=mysql.VARCHAR(length=24),
               comment='获奖类别',
               existing_nullable=True)
        batch_op.alter_column('work_name',
               existing_type=mysql.VARCHAR(length=24),
               comment='作品名称',
               existing_nullable=True)
        batch_op.alter_column('event_name',
               existing_type=mysql.VARCHAR(length=24),
               comment='赛事名称',
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='序号',
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
